### PR TITLE
fix: Resolve TypeScript compilation errors in GitHub integration

### PR DESCRIPTION
**Pull request by anoncam**
## Summary

Fixes the TypeScript compilation errors that were causing the release build to fail after merging PR #95 (GitHub GPG key integration). This enables the release workflow to complete successfully.

## Issues Fixed

This PR resolves all TypeScript errors from the failed release build:

1. ✅ `Property 'github' does not exist on type 'KeysOptions'` (cli/index.ts:885-903)
2. ✅ `Property 'githubName' does not exist on type 'KeysOptions'` (cli/index.ts:897)
3. ✅ `Property 'fingerprint' does not exist on type 'PgpKeyInfo'` (cli/githubUtils.ts:177, 185)
4. ✅ `Type 'string | null' is not assignable to type 'string | undefined'` (cli/githubUtils.ts:186)
5. ✅ `Argument of type 'PgpKeyInfo' is not assignable to parameter of type 'GitHubKeyAddInfo'` (cli/githubUtils.ts:173)
6. ✅ `Type '"github"' is not comparable to ImportOptions source types` (cli/unifiedKeyManager.ts:664)

### 1. cli/index.ts
- Added `github?: string` and `githubName?: string` properties to `KeysOptions` interface

### 2. cli/githubUtils.ts
- Fixed type mismatch by creating proper mapping from `PgpKeyInfo` to `GitHubKeyAddInfo`
- Map `keyId` → `fingerprint` (importPgpKey returns keyId, not fingerprint)
- Convert `email: string | null` → `email?: string` using nullish coalescing operator

### 3. cli/unifiedKeyManager.ts
- Added `'github'` to the `ImportOptions.source` union type

### 4. package-lock.json
- Updated from running `npm install` during verification

## Test Plan

- [x] Run `npm install` to ensure dependencies are installed
- [x] Run `npm run build` to verify TypeScript compilation succeeds
- [x] Verify no TypeScript errors are reported

## Related

- Fixes build failure from PR #95
- Related to issue #94

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by anoncam** [comment]
#94 fixes
